version: "3"

services:
    prometheus:
        image: prom/prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus:/prometheus
        ports:
            - 9090:9090
    
    host:
        image: quay.io/prometheus/node-exporter:latest
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        cap_add:
            - SYS_TIME
        depends_on:
            - prometheus
        command:
            - '--path.rootfs=/host'

    grafana:
        image: grafana/grafana
        restart: unless-stopped
        ports:
            - 3001:3000

volumes:
    prometheus:
